In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3, 4, 5]
myarray = np.array(mylist)
print(myarray)

[1 2 3 4 5]


In [3]:
mylist

[1, 2, 3, 4, 5]

In [6]:
myarray.shape

(5,)

In [9]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.linspace(0, 10, 5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
len(np.linspace(0, 10, 5))