In [ ]:
# https://numpy.org/doc/2.1/reference/ufuncs.html#math-operations

In [21]:
import numpy as np

In [8]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
arr - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [15]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [17]:
np.sqrt(arr ** 2)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [18]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [19]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [20]:
np.max(arr)

9