# Bases array indexing

In [1]:
import numpy as np

arr = np.arange(10) # même chose que range version array numpy
print(arr) # 0, 1, 2, 3, 4, 5, 6, 7, 8, 9

print(arr[2:])
print(arr[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 3 4]


In [26]:
copied_array = arr.copy()
copied_array[2:5] = 2
print(copied_array)
print(arr)

[0 1 2 2 2 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [27]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
arr_2d[0] # on accède à la première ligne

array([ 5, 10, 15])

In [29]:
arr_2d[2][2] # on accède à la troisième ligne et troisième colonne

45

In [30]:
arr_2d[2, 2] # même chose que la ligne précédente

45

In [31]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
arr_2d[:2, 1:] # on prend les deux premières lignes et toutes les colonnes à partir de la deuxième

array([[10, 15],
       [25, 30]])

In [33]:
large_array = np.random.randint(0, 50, size=(10, 10))

print(large_array)

[[18 15 16  0 33 49 19 40 35 15]
 [37 49 38  3 20 35 27 30  2 39]
 [44 33  8 12 16 37 42 25 21 38]
 [37  8 10  9 16 25 22 36 41  9]
 [11 14 31 47  7  2 16 32 24  0]
 [20 38 28  0 41 13 48 10 30 43]
 [47 16 17 22  6 10 26 19 36  3]
 [49 15 11 48 25 20  1  2 24 45]
 [ 6 44 49 46 13 37 11 44 37 12]
 [11 38 40  3 42 28 27 14 32 38]]


In [34]:
large_array[1:2, 4]

array([20])

In [35]:
arr2 = np.arange(1,11)

In [36]:
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]


In [37]:
bool_arr = arr2 > 5 # équivalent de [x > 2 for x in arr2] en list python
print(bool_arr) # [False False  ... True ... etc]

[False False False False False  True  True  True  True  True]


In [40]:
arr2[bool_arr] # on accède aux éléments de arr2 qui sont supérieurs à 5

array([ 6,  7,  8,  9, 10])

In [41]:
arr2[arr2>5] # pour le faire en une seule ligne

array([ 6,  7,  8,  9, 10])

In [42]:
arr[arr<3]

array([0, 1, 2])

In [48]:
arr_2d_new = np.arange(50).reshape(5, 10) # on crée un tableau de 50 éléments et on le reshape en 5 lignes et 10 colonnes
print(arr_2d_new)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [52]:
# entraînement : sélectionner 13 14 et 23 24
arr_2d_new[1:3, 3:5]

array([[13, 14],
       [23, 24]])