# NumPy Exercises

#### Import NumPy as np

In [ ]:
import numpy as np

#### Create an array of 10 zeros 

In [ ]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [ ]:
arr2 = np.ones(10)
print(arr2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [ ]:
arr3 = np.full(10, 5)
print(arr3)

[5 5 5 5 5 5 5 5 5 5]


#### Create an array of the integers from 10 to 50

In [ ]:
arr4 = np.arange(10, 51)
print(arr4)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [ ]:
arr5 = np.arange(10, 51, 2)
print(arr5)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
arr6 = np.arange(0,9).reshape(3, 3) # ✅ on crée un array 1D de 0 à 8, puis on le passe en 2D avec 3 lignes et 3 colonnes
print(arr6)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [ ]:
arr7 = np.eye(3)
print(arr7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [ ]:
num8 = np.random.randint(0, 2) # ✅
print(num8)
num8_alt = np.random.rand(1)
print(num8_alt)

0
[0.6429923]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
arr9 = np.random.randn(2)
print(arr9)
arr9_answer = np.random.randn(25)
print(arr9_answer)
arr9_answer.shape

[ 2.04684433 -0.60872561]
[ 0.07602824  0.96159223  0.69050003 -0.02488442  1.19138386 -2.04763197
 -0.21527872 -0.40076651  0.62315205  0.25502848 -1.70309645 -0.17049044
 -0.44566075  0.26690571  1.51128791  0.54400052 -0.10154469 -1.04929819
 -0.24593531  0.53336111  0.35753806 -0.66564893  0.2388703  -0.91023864
  0.90174435]


(25,)

#### Create the following matrix:

In [ ]:
arr10 = np.arange(1, 101).reshape(10,10)/100  # ✅
print(arr10)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
arr10_alt = np.linspace(0.01, 1, 100).reshape(10,10)
print(arr10_alt)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
arr11 = np.linspace(0, 1, 20)  # ✅ linspace génère un tableau de nombres également espacés sur un intervalle spécifié
print(arr11)

SyntaxError: invalid character '✅' (U+2705) (566715863.py, line 1)

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat2 = mat[2:5, 1:5] #✅ (on pouvait aussi l'écrire mat[2:, 1:])
print(mat2)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
mat3 = mat[-2, -1] # ✅ ou mat[3, 4] avec le premier étant la lligne, le deuxième la colonne
print(mat3)

20


20

In [ ]:
mat4 = mat[0:3, 1:2] # casi ok mais le format attendu est 2D pas 1D, j'avais fait mat[0:3, 1], la soluce est de faire mat[0:3, 1:2] et là on a les mêmes résultats mais en 2D
print(mat4)

[[ 2]
 [ 7]
 [12]]


[ 2  7 12]


In [ ]:
mat5 = mat[-1] #✅
print(mat5)

[21 22 23 24 25]


array([21, 22, 23, 24, 25])

In [ ]:
mat6 = mat[3:5] # ✅
print(mat6)

[[16 17 18 19 20]
 [21 22 23 24 25]]


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
mat7 = np.sum(mat) # ✅ (on pouvait aussi faire mat.sum()
print(mat7)

325


#### Get the standard deviation of the values in mat

In [ ]:
mat8 = np.std(mat)
print(mat8)

7.211102550927978


#### Get the sum of all the columns in mat

In [ ]:
mat9 = mat.sum(axis=0)
print(mat9)

[55 60 65 70 75]


# Great Job!